config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'

  get 'conversations/index'

  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end
	root "static_pages#home"
  devise_for :users
  resources :products, only: [:index, :show] do
    resources :reviews
  end
  resources :categories
  resources :users, :only => [:show]
  resources :suggests, :only => [ :new , :create]
  resources :orders do
    resources :order_items
  end
  get "/search", to: "filters#show"
  resource :cart
   as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
    get "signup" => "devise/registrations#new"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root "static_pages#index"
    resources :categories
    resources :products
    resources :suggests
    resources :orders do
      resources :order_items, only: :index
    end
    resources :users#, only: %i(index destroy)
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items
  enum status: [:pending, :accepted, :refused]
  delegate :email, to: :user, prefix: "user", allow_nil: true
  delegate :username, to: :user, prefix: "user", allow_nil: true

  scope :order_created_at_desc, -> {order created_at: :desc}
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	before_action :find_suggest , only: [:destroy,:edit]

	def index
		@orders = Order.all.order(status: :ASC)
	end

	def destroy
	  	@status = 2
	  	update_status
	end

	def edit
		@status = 1
	  	update_status
	end

	private
	  	def find_suggest
	  		@order = Order.find(params[:id])
	  	end

	  	def update_status
	  		if @order.update_attribute(:status,@status)
		        flash[:success] = "success"
		    else
		        flash[:danger] = "failed"
		    end
		    redirect_to admin_orders_path
	  	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_user!, only: %i(create index destroy)
  before_action :load_order, :check_status, only: :destroy

  def index
    @orders = current_user.orders.page(params[:page]).
      per Settings.paginate.per_page
  end

  def create
    @order = current_user.orders.new
    session[:shopping_cart].each do |item|
      @order.order_items << @order.order_items.new(item)
    end
    if @order.save
      flash[:success] = t ".order_success"
      session[:shopping_cart] = []
    else
      flash[:danger] = t ".order_failed"
    end
    redirect_to orders_path
  end

  def destroy
    if @order.destroy
      flash[:success] = t ".delete_success"
    else
      flash[:danger] = t ".delete_failed"
    end
    redirect_to orders_path
  end


  private

  def load_order
    @order = current_user.orders.find_by id: params[:id]
    return if @order
    flash[:danger] = t "orders.not_found_order"
    redirect_to orders_path
  end

  def check_status
    return if @order.pending?
    flash[:danger] = t "admin.suggests.can_not_delete"
    redirect_to admin_suggests_path
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_order.html.erb
  <tr> 
    <td><%= order.user.name %></td>
    <td><%= order.created_at %></td>
    <td><%= order.total %></td>
    <% if order.pending? %>
      <td class="pending_status" >
        <%= "pending...".capitalize %>    
      </td>
    <% elsif order.accepted? %>
      <td class="accepted_status" >
        <%= "accepted".capitalize %>    
      </td>
    <% else %>
      <td class="rejected_status" >
        <%= "rejected".capitalize %>    
      </td>
    <% end %>
     <td>
        <%= link_to admin_order_order_items_path(order_id: order.id) do %>
          <i class="glyphicon glyphicon-search"></i>
        <% end %>
      <% if order.pending? %>
        <%= link_to edit_admin_order_path(order) do %>
          <i class="glyphicon glyphicon-ok"></i>
        <% end %>
        <%= link_to admin_order_path(order) , method: :delete do %>
          <i class="glyphicon glyphicon-remove"></i>
        <% end %>
      <% end %> 
    </td>
  </tr>

app/views/admin/orders/index.html.erb
<h1>Manage Orders</h1>

<div class="row">
    <div class="col-lg-12">
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th><%= t ".user" %></th>
                  <th><%= t ".date" %></th>
                  <th><%= t ".total" %></th>
                  <th><%= t ".status" %></th>
                  <th><%= t ".function" %></th>
                </tr>
              </thead>
              <tbody id="list-products">
                <%= render @orders%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <%= link_to "Back", admin_root_path %>
    </div>
</div>