config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'

  get 'conversations/index'

  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end
	root "static_pages#home"
  devise_for :users
  resources :products, only: [:index, :show] do
    resources :reviews
  end
  resources :categories
  resources :users, :only => [:show]
  resources :suggests, :only => [ :new , :create]
  resources :orders do
    resources :order_items
  end
  get "/search", to: "filters#show"
  resource :cart
   as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
    get "signup" => "devise/registrations#new"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root "static_pages#index"
    resources :categories
    resources :products
    resources :suggests
    resources :orders do
      resources :order_items, only: :index
    end
    resources :users#, only: %i(index destroy)
  end

end

app/models/product.rb
class Product < ApplicationRecord
  attr_accessor :image# tao bien binh thuong chua ma nhi phan 1 anh
  belongs_to :category
  has_many :order_items, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :reviews
  mount_uploader :image, ImageUploader
  scope :order_created_at_desc, -> {order created_at: :desc}
  scope :category_by, -> (category){where category_id: category}
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :find_product, only: [:destroy,:edit,:update] 

  def index
  	@products = Product.all.order(category_id: :desc)
  end

  def new
  	@product = Product.new
  end

  def create
  	@product = Product.new(product_params)
  	if @product.save
  		redirect_to admin_products_path
  	else
  		render 'new'
  	end
  end

  def edit
  end

  def update
  	if @product.update_attributes(product_params)
  		redirect_to admin_products_path
  	else
  		render 'edit'
  	end
  end

  def destroy
  	if @product.present?
  		@product.destroy
  		flash[:success] = "Delete complete"
  	else
  	end
  	redirect_to admin_products_path
  end

  private 
  	def find_product
  		@product = Product.find(params[:id])
  	end

  	def product_params
  		params.require(:product).permit(:category_id,:name,:image,:price,:quantity,:description)
  	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index

      @products = Product.where(:category_id => params[:category_id]).order_created_at_desc
	end

  def show
  	@product = Product.find_by id: params[:id]
    @reviews = Review.all.for_product(@product.id)
    @rating = 0
    @reviews.each do |review|
      if review.rating 
        @rating += review.rating
      end
    end
    if @reviews.length > 0
      @rating = @rating/@reviews.length
    end
    return if @product
    redirect_to root_url
   #  return if @product
   #  redirect_to root_url
  end
  private

    def find_product
      @product = Product.find(params[:id])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_product.html.erb
  <tr> 
    <td><%= product.category.name %></td>
    <td><%= product.name %></td>
    <td class="image"><%= image_tag product.image_url.to_s %></td>
    <td><%= product.quantity %></td>
    <td><%= product.price %></td>
    <td><%= product.description %></td>

    <td>
        <%= link_to edit_admin_product_path(product) do %>
          <i class="glyphicon glyphicon-edit"></i>
        <% end %>
        <%= link_to admin_product_path(product), method: :delete,
          data: {confirm: t(".you_sure")} do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>
    </td>
  </tr>

app/views/admin/products/edit.html.erb
<h1>Edit</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_for @product, url: admin_product_path(@product), method: :patch do |f| %>
		<%= f.label :category %>
		<%= collection_select(:product, :category_id, Category.all, :id, :name) %>
		<br></br>
		<%= f.label :name%>
		<%= f.text_field :name, class: 'form-control'%>
		<%= f.label :image%>
		<%= f.file_field :image%>
		<%= f.label :price%>
		<%= f.text_field :price, class: 'form-control'%>
		<%= f.label :quantity%>
		<%= f.text_field :quantity, class: 'form-control'%>
		<%= f.label :description%>
		<%= f.text_field :description, class: 'form-control'%>
	    <%= f.submit "Update",class: "btn btn-primary"%>
	<% end %>
  </div>
</div>

app/views/admin/products/index.html.erb
<h1>Manage Products</h1>

<div class="row">
    <div class="col-lg-12">
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th><%= t ".category" %></th>
                  <th><%= t ".name" %></th>
                  <th><%= t ".image" %></th>
                  <th><%= t ".quantity" %></th>
                  <th><%= t ".price" %></th>
                  <th><%= t ".description" %></th>
                  <th><%= t ".function" %></th>
                </tr>
              </thead>
              <tbody id="list-products">
                <%= render @products%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <%= link_to "Back", admin_root_path %>
      <%= link_to "Add", new_admin_product_path %>
    </div>
</div>
<style type="text/css">
  .image img{
    width: 200px;
    height: 200px;
  }
</style>

app/views/admin/products/new.html.erb
<h1>Edit</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_for @product, url: admin_products_path, method: :post do |f| %>
		<%= f.label :category %>
		<%= collection_select(:product, :category_id, Category.all, :id, :name) %>
		<br></br>
		<%= f.label :name%>
		<%= f.text_field :name, class: 'form-control'%>
		<%= f.label :image%>
		<%= f.file_field :image%>
		<%= f.label :price%>
		<%= f.text_field :price, class: 'form-control'%>
		<%= f.label :quantity%>
		<%= f.text_field :quantity, class: 'form-control'%>
		<%= f.label :description%>
		<%= f.text_field :description, class: 'form-control'%>
	    <%= f.submit "Create",class: "btn btn-primary"%>
	<% end %>
  </div>
</div>