config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'

  get 'conversations/index'

  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end
	root "static_pages#home"
  devise_for :users
  resources :products, only: [:index, :show] do
    resources :reviews
  end
  resources :categories
  resources :users, :only => [:show]
  resources :suggests, :only => [ :new , :create]
  resources :orders do
    resources :order_items
  end
  get "/search", to: "filters#show"
  resource :cart
   as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
    get "signup" => "devise/registrations#new"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root "static_pages#index"
    resources :categories
    resources :products
    resources :suggests
    resources :orders do
      resources :order_items, only: :index
    end
    resources :users#, only: %i(index destroy)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :suggests, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :rates, dependent: :destroy
  has_many :reviews

  def current_user? user
    user == self
  end

  has_many :messages
  has_many :conversations, foreign_key: :sender_id
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :find_user , only: [:edit,:update,:destroy]

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
    	@user = User.new(user_params)
    	if @user.save
     		redirect_to admin_users_path
     		flash[:success] = "Success Create"
    	else
    		flash[:danger] = "Cannot Create"
     		render 'new'
    	end
  	end


	def edit
	end

	def update
		if @user.update_attributes(user_params)
			redirect_to admin_users_path
			flash[:success] = "Success Edit"
		else
			flash[:danger] = "Cannot Edit"
			render 'edit'
		end
	end
	
	def destroy
		if @user.present?
      		@user.destroy
      		flash[:success] = "Success Delete"
    	else
    		flash[:success] = "Can't Delete"
		end
    	redirect_to admin_users_path
	end

	private
		def user_params
    		params.require(:user).permit(:name, :email,:phone,:address,:password,
                                   :password_confirmation)
    	end


		def find_user
			@user = User.find(params[:id])
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find_by id: params[:id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_for @user, url: admin_user_path(@user), method: :patch do |f| %>
		<%= f.label :name%>
		<%= f.text_field :name, class: 'form-control'%>
	    <%= f.label :email %>
	    <%= f.email_field :email, class: 'form-control' %>
	    <%= f.label :phone %>
	    <%= f.text_field :phone, class: 'form-control' %>
	    <%= f.label :address %>
	    <%= f.text_field :address, class: 'form-control' %>
	    <%= f.label :password %>
	    <% if @minimum_password_length %>
	    <em>(<%= @minimum_password_length %> characters minimum)</em>
	    <% end %>
	    <%= f.password_field :password, class: 'form-control' %>
	    <%= f.label :password_confirmation %><br />
	    <%= f.password_field :password_confirmation, class: 'form-control' %>
	    <%= f.submit "Update",class: "btn btn-primary"%>
	<% end %>
  </div>
</div>

app/views/admin/users/_user.html.erb
  <tr>   
    <td><%= user.name %></td>
    <td><%= user.address %></td>
    <td><%= user.phone %></td>
    <td><%= user.email %></td>
    <td>
        <%= link_to edit_admin_user_path(user) do %>
          <i class="glyphicon glyphicon-edit"></i>
        <% end %>
        <%= link_to admin_user_path(user), method: :delete,
          data: {confirm: t(".you_sure")} do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>
    </td>
  </tr>

app/views/admin/users/edit.html.erb
<h1>Edit</h1>

<%= render "form" %>

app/views/admin/users/index.html.erb
<h1>Manage users</h1>
<div class="row">
    <div class="col-lg-12">
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th><%= t ".name" %></th>
                  <th><%= t ".address" %></th>
                  <th><%= t ".phone" %></th>
                  <th><%= t ".email" %></th>
                  <th><%= t ".function" %></th>
                </tr>
              </thead>
              <tbody id="list-users">
                <%= render @users%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <%= link_to "Back", admin_root_path %>
      <%= link_to "Add", new_admin_user_path %>
    </div>
</div>

app/views/admin/users/new.html.erb
<h1>Add New User</h1>


<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_for @user ,url: admin_users_path ,method: :post do |f| %>
		<%= f.label :name%>
		<%= f.text_field :name, class: 'form-control'%>
	    <%= f.label :email %>
	    <%= f.email_field :email, class: 'form-control' %>
	    <%= f.label :phone %>
	    <%= f.text_field :phone, class: 'form-control' %>
	    <%= f.label :address %>
	    <%= f.text_field :address, class: 'form-control' %>
	    <%= f.label :password %>
	    <% if @minimum_password_length %>
	    <em>(<%= @minimum_password_length %> characters minimum)</em>
	    <% end %>
	    <%= f.password_field :password, class: 'form-control' %>
	    <%= f.label :password_confirmation %><br />
	    <%= f.password_field :password_confirmation, class: 'form-control' %>
	    <%= f.submit "Create",class: "btn btn-primary"%>
	<% end %>
	</div>
</div>