config/routes.rb
Rails.application.routes.draw do

  get 'messages/index'

  get 'conversations/index'

  resources :conversations, only: [:create] do
    member do
      post :close
    end

    resources :messages, only: [:create]
  end
	root "static_pages#home"
  devise_for :users
  resources :products, only: [:index, :show] do
    resources :reviews
  end
  resources :categories
  resources :users, :only => [:show]
  resources :suggests, :only => [ :new , :create]
  resources :orders do
    resources :order_items
  end
  get "/search", to: "filters#show"
  resource :cart
   as :user do
    get "signin" => "devise/sessions#new"
    post "signin" => "devise/sessions#create"
    delete "signout" => "devise/sessions#destroy"
    get "signup" => "devise/registrations#new"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    root "static_pages#index"
    resources :categories
    resources :products
    resources :suggests
    resources :orders do
      resources :order_items, only: :index
    end
    resources :users#, only: %i(index destroy)
  end

end

app/models/suggest.rb
class Suggest < ApplicationRecord
  belongs_to :user
  enum status: [:pending, :accepted, :refused]
end

app/controllers/admin/suggests_controller.rb
class Admin::SuggestsController < ApplicationController
  before_action :find_suggest, only: [:destroy,:edit,:update]  


  def index
  	@suggests = Suggest.all.order(status: :ASC)
  end

  def destroy
  	@status = 2
  	if @suggest.present?
  		update_status
  	else
  	end
  	redirect_to admin_suggests_path
  end

  def edit
  	@product = Product.new
  	@product.name = @suggest.name
  	@product.price = @suggest.price
  	@product.description = @suggest.description
  end

  def update
  	@status = 1
  	@product = Product.new(product_params)
  	if @product.save
  		update_status
  		redirect_to admin_suggests_path
  	else
  		render 'edit'
  	end
  end

  private
  	def find_suggest
  		@suggest = Suggest.find(params[:id])
  	end

  	def product_params
  		params.require(:product).permit(:category_id,:name,:image,:price,:quantity,:description)
  	end

  	def update_status
      if @suggest.update_attribute(:status,@status)
        flash[:success] = "success"
      else
        flash[:danger] = "failed"
      end
  	end

end

app/controllers/suggests_controller.rb
class SuggestsController < ApplicationController
  
  def new
  	@suggest = Suggest.new
  end

  def create
  	@suggest = Suggest.new(suggest_params)
  	@suggest.user_id = current_user.id
  	@suggest.status = 0
  	if @suggest.save || product_have
  		redirect_to root_path
  		flash[:success] = "Suggest success"
  	else
  		flash[:danger] = "This product haved"
  	end
  end

  private

  	def suggest_params
  		params.require(:suggest).permit(:name,:price,:quantity,:description)
  	end

  	def product_have
  		@product_name = Product.find_by name: @suggest.name
  	end

end

app/views/admin/suggests/_suggest.html.erb
  <tr>
    <td><%= suggest.user.name %></td>
    <td><%= suggest.name %></td>
    <td><%= suggest.price %></td>
    <td><%= suggest.description %></td>
    <% if suggest.pending? %>
      <td class="pending_status" >
        <%= "pending...".capitalize %>    
      </td>
    <% elsif suggest.accepted? %>
      <td class="accepted_status" >
        <%= "accepted".capitalize %>    
      </td>
    <% else %>
      <td class="rejected_status" >
        <%= "rejected".capitalize %>    
      </td>
    <% end %>
    <td>
      <% if suggest.pending? %>
        <%= link_to edit_admin_suggest_path(suggest) do %>
          <i class="glyphicon glyphicon-ok"></i>
        <% end %>
        <%= link_to admin_suggest_path(suggest), method: :delete do %>
          <i class="glyphicon glyphicon-remove"></i>
        <% end %>
      <% end %> 
    </td>
  </tr>

app/views/admin/suggests/edit.html.erb
<h1>Edit</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
	<%= form_for @product, url: admin_suggest_path, method: :patch do |f| %>
		<%= f.label :category %>
		<%= collection_select(:product, :category_id, Category.all, :id, :name) %>
		<br></br>
		<%= f.label :name%>
		<%= f.text_field :name, class: 'form-control'%>
		<%= f.label :image%>
		<%= f.file_field :image%>
		<%= f.label :price%>
		<%= f.text_field :price, class: 'form-control'%>
		<%= f.label :quantity%>
		<%= f.text_field :quantity, class: 'form-control'%>
		<%= f.label :description%>
		<%= f.text_field :description, class: 'form-control'%>
	    <%= f.submit "Accept",class: "btn btn-primary"%>
	<% end %>
  </div>
</div>

app/views/admin/suggests/index.html.erb
<h1>Manage Suggests</h1>
<div class="row">
    <div class="col-lg-12">
        <div class="panel-body">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th><%= t ".user" %></th>
                  <th><%= t ".name" %></th>
                  <th><%= t ".price" %></th>
                  <th><%= t ".description" %></th>
                  <th><%= t ".status" %></th>
                  <th><%= t ".function" %></th>
                </tr>
              </thead>
              <tbody id="list-users">
                <%= render @suggests%>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <%= link_to "Back", admin_root_path%>
    </div>
</div>